In [180]:
import sys
sys.path.append('/Users/leah/Columbia/courses/19summer/SocialBehavior/SocialBehaviorptc')

In [1]:
import torch
import numpy as np

In [4]:
def f(*args):
    for i, a in enumerate(args):
        print(i, a)

In [6]:
f("apple", "peach", "lemon")

0 apple
1 peach
2 lemon


In [10]:
def f1():
    return "apple", "pear"

In [11]:
def f2():
    return ("haha", ) + f1()

In [12]:
f2()

('haha', 'apple', 'pear')

In [32]:
class toy:
    def __init__(self, a, b):
        self.a = a
        self.b = b
        
    @property
    def params(self):
        return self.a, self.b
    
    @params.setter
    def params(self, values):
        self.a = values[0]
        self.b = values[1]

In [33]:
td = toy(0, 2)

In [34]:
td.params

(0, 2)

In [35]:
td.params = (3,5)

In [36]:
td.params

(3, 5)

In [39]:
x1 = torch.tensor([2.5, 3.5])
x2 = torch.tensor([6.0, 7.0])
x3 = torch.tensor([8.0, 9.0])
x = [x1, x2, x3]

In [49]:
torch.stack(x, dim=0)

tensor([[2.5000, 3.5000],
        [6.0000, 7.0000],
        [8.0000, 9.0000]])

In [50]:
T = 10
D = 4
Df = 3
K = 2

In [51]:
t = torch.empty(T, K, D, 1)

In [62]:
out = torch.squeeze(t, dim=-1)

In [63]:
out.shape

torch.Size([10, 2, 4])

In [77]:
features_a = torch.ones(T, K, D, 1)

In [78]:
features_b = torch.zeros(T, K, D, 1)

In [79]:
features = torch.cat((features_a, features_b), dim=2)

In [76]:
torch.allclose(features[:,:,3:],features_b) 

True

In [88]:
def f(a, b, **kwargs):
    print(a)
    print(b)
    for k, v in kwargs.items():
        print("{0} = {1}".format(k, v))

In [89]:
f(1,2)

1
2


In [91]:
f(1,2, momentum=[1,2,3], features=[4,5,6])

1
2
momentum = [1, 2, 3]
features = [4, 5, 6]


In [100]:
def f2(momentum=None, features=None):
    print(momentum)
    print(features)

In [101]:
def f3(a, b, **kwargs):
    f2(**kwargs)

In [102]:
f3(0, 1, momentum=[1,2,3], features=[4,5,6])

[1, 2, 3]
[4, 5, 6]


In [105]:
s = torch.empty(T, 2)

In [107]:
torch.norm(s, dim=1)

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 4.6566e-10, 4.6566e-10])

In [108]:
def f():
    pass
    print('hi')

In [109]:
f()

hi


In [117]:
T = 10
D = 2
K = 3

lags = 3

In [118]:
data = torch.empty(T, D)

In [132]:
out1 = torch.ones(2, 1)
out2 = torch.zeros(2, 1)

In [137]:
torch.cat((out1, out2), dim=0)

tensor([[1.],
        [1.],
        [0.],
        [0.]])

In [140]:
data[-2:].shape

torch.Size([2, 2])

In [141]:
x = torch.ones(2)

In [142]:
y = torch.zeros(2)

In [146]:
torch.cat((x,y), dim=0)

tensor([1., 1., 0., 0.])

In [159]:
def f():
    return 2,

In [160]:
f() + (2,3)

(2, 2, 3)

In [155]:
out + (3,)

(2,)

In [162]:
d = {"apple": "red", "lemon": "yellow"}

In [164]:
d.get("apple", None)

'red'

In [176]:
def f(a, b, **kwargs):
    m = kwargs.get("apple", None)
    print(kwargs)
    if m is None:
        return print("No apple found.")
    else:
        print(m)
    

In [177]:
f(2,3, apple="haha")

{'apple': 'haha'}
haha


In [178]:
f(2,3)

{}
No apple found.


In [175]:
{}.get("what", None)

In [188]:
from ssm_ptc.distributions.truncatednormal import TruncatedNormal
from ssm_ptc.distributions.logitnormal import LogitNormal

In [182]:
K = 3
D = 4

In [183]:
mus = torch.zeros((K, D), dtype=torch.float64)

In [184]:
log_sigmas_init = torch.tensor(np.log(np.ones((K, D))), dtype=torch.float64)

In [185]:
bounds = torch.tensor([[-20, 20], [-20, 20], [-20, 20], [-20, 20]], dtype=torch.float64)

In [194]:
p_init = TruncatedNormal(mus=mus, log_sigmas=log_sigmas_init, bounds=bounds)

In [195]:
data0 = torch.randn(D, dtype=torch.float64)

In [196]:
log_prob = p_init.log_prob(data0)

In [197]:
log_prob.shape

torch.Size([3, 4])