In [1]:
import sys
sys.path.append("/Users/leah/Columbia/courses/19summer/SocialBehavior/SocialBehaviorptc")

In [3]:
import numpy as np
import torch

from ssm_ptc.models.hmm import HMM

import matplotlib.pyplot as plt
import joblib

In [5]:
model_dir = "/Users/leah/Columbia/courses/19summer/SocialBehavior/rslts/hmm/0930_hmm/v05_K10_8by8_D191001_212523/checkpoint_3/"

In [6]:
model = joblib.load(model_dir + "model")

In [17]:
model.observation

In [9]:
model.observation.mus.shape

torch.Size([10, 4])

In [16]:
for k in range(10):
    print(model.observation.mus[k].detach().numpy())

[1.97654875 0.91862295 0.95173686 0.9331779 ]
[5.96887698 7.08909672 5.50170155 4.31583932]
[0.85901315 0.84331426 1.87619206 0.84007423]
[1.06959169 1.0757271  1.03145474 2.06840414]
[2.09063064e-33 2.97539380e-33 1.90194837e-33 3.33352355e-33]
[2.13413537e-33 3.02508276e-33 1.93248318e-33 3.39251201e-33]
[2.09485254e-33 2.97375093e-33 1.89930760e-33 3.33610368e-33]
[2.22391828e-33 3.17822148e-33 2.03218164e-33 3.55933339e-33]
[2.21929258e-33 3.16154817e-33 2.01956682e-33 3.54607188e-33]
[2.20722906e-33 3.18586231e-33 2.04020135e-33 3.55906750e-33]


In [ ]:
# try HMM to single animal first
# try 4 by 4 K, and set mus to be 16 different locations
# increase learning rates